services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - spring-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bankdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
